### PR TITLE
Sprint1

### PR DESCRIPTION
**Pull request by angelavu**
Finish HW-2 DevOps by merging Sprint1 into master.

Features from Sprint1:
- Added base project and Material-UI @angelavu 
- Added Material-UI Homepage and calculator styling @benjaminvinicky 
- Added calculator design with Material-UI @mjosephwarren 
- Added calculator functionality @jamesp21

### CODE REVIEW

**Comment by mjosephwarren** [comment]
User Stories #1 and #4 are complete. I think Sprint1 branch is ready to merge with Master.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamesp21** [comment]
Everything works and looks good. Sprint complete!

**Review by mjosephwarren — APPROVED** [review]
Review complete!

**Review by jamesp21 — APPROVED** [review]
approve!

**Comment by angelavu** [comment]
approve!

**Review by benjaminvinicky — APPROVED** [review]

**Pull request merged**
